apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/rewrite-target":"/","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"creationTimestamp":"2021-04-11T22:41:58Z","generation":3,"managedFields":[{"apiVersion":"extensions/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:nginx.ingress.kubernetes.io/rewrite-target":{},"f:nginx.ingress.kubernetes.io/ssl-redirect":{}}}},"manager":"kubectl-create","operation":"Update","time":"2021-04-11T22:41:58Z"},{"apiVersion":"extensions/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:loadBalancer":{"f:ingress":{}}}},"manager":"nginx-ingress-controller","operation":"Update","time":"2021-04-11T22:42:23Z"},{"apiVersion":"extensions/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:rules":{}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-04-11T23:19:54Z"}],"name":"ingress-wear-watch","namespace":"app-space","resourceVersion":"6243","selfLink":"/apis/extensions/v1beta1/namespaces/app-space/ingresses/ingress-wear-watch","uid":"43c6d236-e649-4d5d-8ccd-9d9655585969"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"wear-service","servicePort":8080},"path":"/wear","pathType":"ImplementationSpecific"},{"backend":{"serviceName":"video-service","servicePort":8080},"path":"/stream","pathType":"ImplementationSpecific"},{"backend":{"serviceName":"food-service","servicePort":8080},"path":"/eat","pathType":"ImplementationSpecific"},{"backend":{"serviceName":"pay-service","servicePort":8282},"path":"/pay","pathType":"ImplementationSpecific"}]}}]},"status":{"loadBalancer":{"ingress":[{}]}}}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: "2021-04-11T22:41:58Z"
  generation: 4
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:nginx.ingress.kubernetes.io/rewrite-target: {}
          f:nginx.ingress.kubernetes.io/ssl-redirect: {}
    manager: kubectl-create
    operation: Update
    time: "2021-04-11T22:41:58Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: nginx-ingress-controller
    operation: Update
    time: "2021-04-11T22:42:23Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:rules: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-11T23:28:23Z"
  name: ingress-wear-watch
  namespace: app-space
  resourceVersion: "7508"
  selfLink: /apis/extensions/v1beta1/namespaces/app-space/ingresses/ingress-wear-watch
  uid: 43c6d236-e649-4d5d-8ccd-9d9655585969
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: wear-service
          servicePort: 8080
        path: /wear
        pathType: ImplementationSpecific
      - backend:
          serviceName: video-service
          servicePort: 8080
        path: /stream
        pathType: ImplementationSpecific
      - backend:
          serviceName: food-service
          servicePort: 8080
        path: /eat
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - {}
